name: Build and Push Docker image @ghcr.io
description: Build and push Docker image to GitHub Container Registry (ghcr.io)

on:
  workflow_call:
    inputs:
      build_env_file:
        required: false
        type: string
        default: ".github/.build.env"
      build_image_name:
        description: "Name of the image to build (e.g., python-base)"
        required: true
        type: string
      build_image_tags:
        description: "Comma-separated list of tags to apply to the image (e.g., 3.12.2-slim, latest)"
        required: true
        type: string
jobs:

  build_and_test:
    name: Test image ${{ inputs.build_image_name }}:${{ inputs.build_image_tags }}
    runs-on: ubuntu-latest

    outputs:
      build_args: ${{ steps.buildargs.outputs.BUILD_ARGS }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Download build-env artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build_env_file }}

      - name: Prepare build args from .build.env
        id: buildargs
        run: |
          # Remove comments and empty lines, format as build-args
          grep -v '^\s*#' .build.env | grep -v '^\s*$' > build_args.txt
          echo "BUILD_ARGS<<EOF" >> $GITHUB_OUTPUT
          cat build_args.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('.build.env ') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build local image to test
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          build-args: ${{ steps.buildargs.outputs.BUILD_ARGS }}
          tags: local/image
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Test local image
        run: |
          docker run --rm \
            -v $(pwd)/:/build/ -w /build \
            --entrypoint "./scripts/test-image.sh" \
            local/image

      - name: Scan the image
        uses: anchore/sbom-action@v0
        with:
          image: local/image
          artifact-name: local-image.${{ hashFiles('.build.env ') }}.spdx.json


  build_and_push:
    name: Push image ${{ inputs.build_image_name }}:${{ inputs.build_image_tags }} @ghcr.io
    runs-on: ubuntu-latest
    needs: build_and_test
    if: ${{ success() && (startsWith(github.ref, 'refs/tags/') || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') }}
    permissions:
      contents: read
      packages: write
    concurrency:
      group: "${{ github.repository_id }}-build-and-push"

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Download build-env artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build_env_file }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('.build.env ') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Setup Docker metadata
        id: setup_metadata
        run: |

          readarray -td, image_tags <<<"${{ inputs.build_image_tags }},"; unset 'image_tags[-1]';
          for image_tag in "${image_tags[@]}"; do
            trimmed_tag=$(echo "$image_tag" | xargs)
            META_TAGS+="type=raw,value=${trimmed_tag}\n"
            DELETE_TAGS=${DELETE_TAGS:+$DELETE_TAGS,}${trimmed_tag}
          done

          # META_TAGS contains a list of meta tags to be applied to the image.
          echo "meta_tags<<EOF" >> $GITHUB_OUTPUT
          echo -e "$META_TAGS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          # DELETE_TAGS contains a comma-separated list of image tags to be deleted from the GitHub Container Registry.
          echo "delete_tags=$DELETE_TAGS" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.build_image_name }}
          tags: |
            ${{ steps.setup_metadata.outputs.meta_tags}}
          flavor: |
            latest=false

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old image @ghcr.io
        uses: dataaxiom/ghcr-cleanup-action@v1
        continue-on-error: true
        with:
          package: "${{ inputs.build_image_name }}"
          delete-tags: ${{ steps.setup_metadata.outputs.delete_tags}}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ needs.build_and_test.outputs.build_args }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          sbom: true
          provenance: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}