name: Validate Dockerfile
description: Validate Dockerfile

on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: addnab/docker-run-action@v3
        with:
          image: hadolint/hadolint:latest-alpine
          options:  -v ${{ github.workspace }}:/app
          run: sh -c 'hadolint --version && cd app && echo "Checking..." && hadolint Dockerfile && echo "Done"'
