name: Validate
description: Validate Dockerfile and shell scripts

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - scripts/**/*.sh
  pull_request:
    paths:
      - Dockerfile
      - scripts/**/*.sh

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: addnab/docker-run-action@v3
        with:
          image: hadolint/hadolint:latest-alpine
          options:  -v ${{ github.workspace }}:/app
          run: sh -c 'hadolint --version && cd app && echo "Checking..." && hadolint Dockerfile && echo "Done"'

      - name: Run ShellCheck
        uses: addnab/docker-run-action@v3
        with:
          image: koalaman/shellcheck-alpine:latest
          options:  -v ${{ github.workspace }}:/app
          run: sh -c 'shellcheck --version && cd app && echo "Checking..." && shellcheck scripts/*.sh && echo "Done"'